name: tagged_todos_organizer
description: Todos manager organized by tags.
publish_to: 'none' 
version: 1.7.2
#fl 3.22.3
environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  csv: ^6.0.0
# file_picker: 10.1.0 keep due to bugs in latest versions
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  open_filex: ^4.7.0
  path: ^1.9.1
  path_provider: ^2.1.5
  process_run: ^1.2.4
  sembast: ^3.8.5+1
  url_launcher: ^6.3.2
  notes_on_image:
    git:
      url: https://github.com/lavruh/NotesOnImage.git
  photo_data_picker:
    git:
      url: https://github.com/lavruh/photo_data_picker.git
  restart_app:
    git: https://github.com/lavruh/restart_app.git
  get: ^4.7.2
  flutter_slidable: ^4.0.0
  go_router: ^16.0.0
  archive: ^4.0.7
  flutter_fancy_tree_view: ^1.6.0
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  riverpod_annotation: ^2.6.1
  filesystem_picker: ^4.1.0
  camerawesome: ^2.5.0
  popover: ^0.3.1
  flutter_local_notifications: ^19.4.0  #Linux is not supported in current version
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  data_table_2: ^2.6.0
  auto_size_text_field: ^2.2.4

dev_dependencies:
  build_runner: ^2.4.15
  mockito: ^5.4.5
  riverpod_generator: ^2.6.5
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/technology.png"

